### ISSUE TITLE
Poor framerate in stage 1-2

### ISSUE THREAD

**Issue by samaralarkin** [GalaxyTrail/GFR_bugs#32]
Still playable, but very noticeable, and none of the other demo stages are affected. My hardware should be more than adequate. Happy to test further as needed.

**Comment by FlutterSprite** [comment]
Would you mind sharing your specs? 1-2 is the most demanding level, and I find that having a good CPU is more of a factor than GPU. Something about having lots of different enemies in one level does provide quite a performance hit - I'll look into optimizing where I can, but only so much can be done with my resources, I'm afraid!

**Comment by samaralarkin** [comment]
Windows 10 Pro
Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
48GB RAM
GeForce GTX 660

I thought it might have something to do with all the enemies, too, but it doesn't get any better as they're defeated. It does seem to get better or worse depending on where I am in the level, but I haven't noticed a pattern.

**Comment by FlutterSprite** [comment]
That's very strange! That should be more than enough - heck, your computer's better than mine - though I have a 3.2 GHz i5, rather than a 2.67GHz i7. The game doesn't support multi-threading, so having more powerful individual cores probably makes it perform better. In any case, I'll see what I can do about optimizing this level in particular!

**Comment by FlutterSprite** [comment]
Closing this for now!
