### ISSUE TITLE
5-2 - "Buddy-icicle" and fallen icicles' sound issue

### ISSUE THREAD

**Issue by SP3Ctator** [GalaxyTrail/GFR_bugs#86]
https://youtu.be/55XaScML4gE

This is a video depiction of an issue with fallen icicles in the boss fight in 5-2. After the boss slams the ground and makes the icicle fall from the ceiling, there sometimes be a "buddy-icicle" that will not break after touching the ground but lie on its side indefinitely instead. It can be dropped and thrown around freely without breaking, and will only be destroyed upon hitting the boss.

Its existence will cause another issue, where any icicle grabbed and then dropped by Rena will be producing its "icicle hitting the floor" sound for almost every frame, resulting in a very loud noise. Dropped icicles cease such behavior after the "buddy-icicle" is destroyed.

**Comment by FlutterSprite** [comment]
I haven't been able to completely eliminate the 'buddy-icicle' problem, but I have mitigated it somewhat - formerly 'buddy' icicles now just get destroyed immediately upon hitting the ground instead of falling on their side. This should solve the bugs associated with it and turn it into a minor cosmetic quirk.
